# Generated by Django 5.0.6 on 2024-05-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
