# Generated by Django 5.0.6 on 2024-05-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
